# Generated by Django 5.0.1 on 2024-07-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightstatus',
            name='flight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
    ]
